config:
	make -C buildroot BR2_EXTERNAL=`pwd`/external raspberrypi4_64_defconfig

elehbr:
	make -C buildroot BR2_EXTERNAL=`pwd`/external elehbr

show-info:
	make -C buildroot BR2_EXTERNAL=`pwd`/external show-info

all:
	make -C buildroot BR2_EXTERNAL=`pwd`/external all
